[package]
name = "choosy_embed"
version = "0.1.0"
authors = ["Tommi Virtanen <tv@eagain.net>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[build-dependencies]
anyhow = "1.0.56"
cargo_metadata = "0.14.2"
wasm-bindgen-cli = { version = "0.2.81", features = ["vendored-openssl"] }
