[package]
name = "choosy_frontend"
version = "0.1.0"
authors = ["Tommi Virtanen <tv@eagain.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.40"
choosy_protocol = { path = "../protocol" }
console_error_panic_hook = "0.1.6"
gloo = "0.2.1"
js-sys = "0.3.51"
serde = "1.0.126"
wasm-bindgen = "0.2.74"
yew = "0.18.0"
regex = "1.5.4"
