[package]
name = "choosy_frontend"
version = "0.1.0"
authors = ["Tommi Virtanen <tv@eagain.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.38"
choosy_protocol = { path = "../protocol" }
console_error_panic_hook = "0.1.6"
gloo = "0.2.1"
js-sys = "0.3.47"
serde = "1.0.123"
wasm-bindgen = "0.2.70"
yew = "0.17.4"
