[package]
name = "sleigh"
version = "0.1.0"
authors = ["Tommi Virtanen <tv@eagain.net>"]
edition = "2018"

[dependencies]
bincode = "1.3.3"
lazy_static = "1.4.0"
serde = "1.0.136"
sled = "0.34.7"
thiserror = "1.0.30"
