[package]
name = "choosy_protocol"
version = "0.1.0"
authors = ["Tommi Virtanen <tv@eagain.net>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
