[package]
name = "choosy"
version = "0.1.0"
authors = ["Tommi Virtanen <tv@eagain.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.9.0", features = ["attributes", "unstable"] }
choosy_embed = { path = "../embed" }
choosy_protocol = { path = "../protocol" }
mpv_remote = { path = "../mpv_remote" }
http-types = "2.11.1"
im = "15.0.0"
scopeguard = "1.1.0"
serde = { version = "1.0.126", features = ["derive"] }
tide = "0.16.0"
tide-websockets = "0.3.0"
walkdir = "2.3.2"
