[package]
name = "choosy"
version = "0.1.0"
authors = ["Tommi Virtanen <tv@eagain.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
async-std = { version = "1.9.0", features = ["attributes", "unstable"] }
choosy_embed = { path = "../embed" }
choosy_protocol = { path = "../protocol" }
http-types = "2.10.0"
im = "15.0.0"
scopeguard = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
tide = "0.16.0"
tide-websockets = "0.2.0"
